version: '3'
services: 
  www: 
    build: './'
    volumes: 
      - "./html/:/var/www/html/"
      - "./database/:/var/www/database/"
    ports:
      - 80:80
      - 443:443
    environment:
      - DB_PATH=/var/www/database/