version: '3'
services: 
  www: 
    build: './php/'
    volumes: 
      - "./php/:/var/www/html"
      - "./database/:/tmp/database/"
    ports:
      - 80:80
      - 443:443
    environment:
      - DB_PATH=/tmp/database/